# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redbag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=10)),
                ('xuhao', models.CharField(max_length=10)),
                ('single', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
